package gui.tabla_de_simbolos;

import tabla_de_simbolos.TablaSimbolos;

/**
 * Ventana de utilidad para ver la tabla de simbolos.
 * 
 * @author Grupo 3, Javier Salcedo Gomez
 */
public class MarcoTabla extends javax.swing.JFrame {

    // VARIABLES
    TablaSimbolos _tablaDeSimbolos;
    InsertarToken _insertarToken;
    Simular _simular;

    /**
     * Constructor de la clase MarcoTabla.
     * 
     * @param tabla Tabla de simbolos asociada.
     */
    public MarcoTabla(TablaSimbolos tabla) {
        
        initComponents();
        
        _tablaDeSimbolos = tabla;
        _simular = new Simular(this);
        _simular.setSize(1100, 600);
        setSize(1100, 600);
        setContentPane(_simular);
    }

    /**
     * Devuelve la tabla de simbolos.
     * 
     * @return La tabla de simbolos.
     */
    public TablaSimbolos getTablaDeSimbolos() {
        
        return _tablaDeSimbolos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabla Símbolos");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
